// dart format width=80
// GENERATED BY pretty_tostring — DO NOT MODIFY

part of 'models.dart';

// **************************************************************************
// PrettyGenerator
// **************************************************************************

// pretty_tostring for Comment
extension CommentPrettyToString on Comment {
  String prettyToString({int indent = 0}) {
    return _prettyComment(this, indent);
  }
}

String _prettyComment(Comment instance, int indent) {
  final String i = '\t' * indent;
  final String ii = '\t' * (indent + 1);
  final StringBuffer buffer = StringBuffer();
  buffer.writeln('${i}Comment(');
  buffer.writeln(
    "${ii}author: ${_prettyValueForComment(instance.author, indent + 1)},",
  );
  buffer.writeln(
    "${ii}text: ${_prettyValueForComment(instance.text, indent + 1)},",
  );
  buffer.write('${i})');
  return buffer.toString();
}

String _prettyValueForComment(Object? value, int indent) {
  final String i = "\t" * indent;
  final String ii = "\t" * (indent + 1);

  if (value == null) {
    return 'null';
  }

  if (value is num || value is bool) {
    return value.toString();
  }

  if (value is String) {
    return '"$value"';
  }

  if (value is List) {
    if (value.isEmpty) {
      return '[]';
    }
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('[');
    for (final Object? item in value) {
      buffer.writeln(_prettyValueForComment(item, indent + 1));
    }
    buffer.write('$i]');
    return buffer.toString();
  }

  if (value is Map) {
    if (value.isEmpty) {
      return '{}';
    }
    final List<Object?> keys = value.keys.toList()
      ..sort((a, b) => a.toString().compareTo(b.toString()));
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('{');
    for (final Object? key in keys) {
      final Object? v = value[key];
      buffer.write('$ii$key: ');
      buffer.writeln(_prettyValueForComment(v, indent + 1));
    }
    buffer.write('$i}');
    return buffer.toString();
  }

  final String raw = value.toString();
  if (raw.contains('(') && raw.contains(')')) {
    return raw.replaceAll('\n', '\n$i');
  }

  return value.toString();
}

// pretty_tostring for Article
extension ArticlePrettyToString on Article {
  String prettyToString({int indent = 0}) {
    return _prettyArticle(this, indent);
  }
}

String _prettyArticle(Article instance, int indent) {
  final String i = '\t' * indent;
  final String ii = '\t' * (indent + 1);
  final StringBuffer buffer = StringBuffer();
  buffer.writeln('${i}Article(');
  buffer.writeln(
    "${ii}comments: ${_prettyValueForArticle(instance.comments, indent + 1)},",
  );
  buffer.writeln("${ii}email: ${obfuscateValue(instance.email)},");
  buffer.writeln(
    "${ii}id: ${_prettyValueForArticle(instance.id, indent + 1)},",
  );
  buffer.writeln(
    "${ii}title: ${_prettyValueForArticle(instance.title, indent + 1)},",
  );
  buffer.write('${i})');
  return buffer.toString();
}

String _prettyValueForArticle(Object? value, int indent) {
  final String i = "\t" * indent;
  final String ii = "\t" * (indent + 1);

  if (value == null) {
    return 'null';
  }

  if (value is num || value is bool) {
    return value.toString();
  }

  if (value is String) {
    return '"$value"';
  }

  if (value is List) {
    if (value.isEmpty) {
      return '[]';
    }
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('[');
    for (final Object? item in value) {
      buffer.writeln(_prettyValueForArticle(item, indent + 1));
    }
    buffer.write('$i]');
    return buffer.toString();
  }

  if (value is Map) {
    if (value.isEmpty) {
      return '{}';
    }
    final List<Object?> keys = value.keys.toList()
      ..sort((a, b) => a.toString().compareTo(b.toString()));
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('{');
    for (final Object? key in keys) {
      final Object? v = value[key];
      buffer.write('$ii$key: ');
      buffer.writeln(_prettyValueForArticle(v, indent + 1));
    }
    buffer.write('$i}');
    return buffer.toString();
  }

  final String raw = value.toString();
  if (raw.contains('(') && raw.contains(')')) {
    return raw.replaceAll('\n', '\n$i');
  }

  return value.toString();
}

// **************************************************************************
// PrettySharedHelperGenerator
// **************************************************************************

// === pretty_tostring shared helper ===

String obfuscateValue(Object? value) {
  if (value == null) return 'null';

  final RegExp email = RegExp(r'^([^@]{1})([^@]*)(@)([^\.]+)(.*)$');
  final match = email.firstMatch(value.toString());
  if (match != null) {
    final first = match.group(1);
    final middle = match.group(2)!.replaceAll(RegExp(r'.'), '*');
    final domainFirst = match.group(4)!.replaceAll(RegExp(r'.'), '*');
    final rest = match.group(5);
    return '"$first$middle@$domainFirst$rest"';
  }

  if (value is String && value.length >= 2) {
    final first = value[0];
    final last = value[value.length - 1];
    return "\"$first${'*' * (value.length - 2)}$last\"";
  }

  if (value is num) return '"***"';

  return '"***"';
}
