import 'package:build/build.dart';

import 'package:pretty_tostring/src/generator.dart';
import 'package:pretty_tostring/src/shared_helper_generator.dart';
import 'package:source_gen/source_gen.dart';

Builder prettyBuilder(BuilderOptions options) {
  return PartBuilder(
    <Generator>[const PrettyGenerator(), const PrettySharedHelperGenerator()],

    '.pretty.g.dart',
    header: '// GENERATED BY pretty_tostring — DO NOT MODIFY',
  );
}
